"""
plotly_dashboard.py
====================
Assembles multiple Plotly figures into a single, self-contained, styled
HTML dashboard file (no server required — opens directly in a browser).

This is deliberately framework-free (no Dash/Streamlit dependency) so the
output is a static artifact that can be emailed, hosted on any static file
server, or opened locally — while still being fully interactive (hover,
zoom, pan) thanks to Plotly.js bundled inline.

The architecture leaves a clear seam for a future Streamlit or Dash app:
each ``build_*`` method returns a ``go.Figure`` that could equally be
rendered inside ``st.plotly_chart(fig)``.
"""

from __future__ import annotations

from pathlib import Path

import plotly.graph_objects as go
import plotly.io as pio

from manufacturing_analytics.utils.logger import get_logger

logger = get_logger(__name__)

DASHBOARD_CSS = """
<style>
    body { font-family: 'Segoe UI', Arial, sans-serif; background:#f4f6f9; margin:0; padding:0; }
    .dash-header { background: linear-gradient(90deg,#1f4e78,#2c6ea6); color:white;
                    padding:24px 32px; }
    .dash-header h1 { margin:0; font-size:26px; }
    .dash-header p { margin:4px 0 0; opacity:0.85; font-size:13px; }
    .dash-grid { display:grid; grid-template-columns: repeat(auto-fit, minmax(460px, 1fr));
                  gap:20px; padding:24px 32px; }
    .dash-card { background:white; border-radius:10px; box-shadow:0 1px 4px rgba(0,0,0,0.08);
                  padding:12px; }
    .dash-card.full { grid-column: 1 / -1; }
    .dash-footer { text-align:center; color:#888; font-size:12px; padding:16px; }
</style>
"""


class DashboardBuilder:
    """Combines Plotly figures into a single responsive HTML dashboard page."""

    def __init__(self, title: str, subtitle: str = ""):
        self.title = title
        self.subtitle = subtitle
        self._sections: list[tuple[go.Figure, bool]] = []  # (figure, full_width)

    def add_figure(self, fig: go.Figure, full_width: bool = False) -> "DashboardBuilder":
        """Add a Plotly figure card to the dashboard (chainable)."""
        self._sections.append((fig, full_width))
        return self

    def render_html(self) -> str:
        """Render all added figures into one HTML document string.

        Plotly.js is loaded from the CDN (a single small <script> tag) rather
        than bundled inline in every figure's HTML — bundling it once per
        figure otherwise inflates the file by several MB for no benefit,
        since the CDN copy is cached by the browser across all figures.
        """
        cards_html = []
        for fig, full_width in self._sections:
            fig_html = pio.to_html(
                fig, include_plotlyjs=False, full_html=False, config={"responsive": True}
            )
            css_class = "dash-card full" if full_width else "dash-card"
            cards_html.append(f'<div class="{css_class}">{fig_html}</div>')

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>{self.title}</title>
<script src="https://cdn.plot.ly/plotly-2.32.0.min.js"></script>
{DASHBOARD_CSS}
</head>
<body>
<div class="dash-header">
    <h1>{self.title}</h1>
    <p>{self.subtitle}</p>
</div>
<div class="dash-grid">
    {''.join(cards_html)}
</div>
<div class="dash-footer">Generated by Manufacturing Analytics Platform</div>
</body>
</html>"""
        return html

    def save(self, out_path: str | Path) -> Path:
        """Render and write the dashboard HTML to disk."""
        out_path = Path(out_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(self.render_html(), encoding="utf-8")
        logger.success("Dashboard saved -> {}", out_path)
        return out_path
